name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7

      - name: Setup and install dependencies
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # ratchet:pnpm/setup@v3

      - name: Build
        run: pnpm run build

      - name: Prepare for publish
        run: pnpm run prepare-publish

      - name: Publish
        run: pnpm publish --access public --provenance --no-git-checks dist
