name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7

      - name: Setup and install dependencies
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # ratchet:pnpm/setup@v2

      - name: Build
        run: pnpm run build

      - name: Publish
        env:
          NPM_CONFIG_PROVENANCE: true
        run: pnpm publish --access public --no-git-checks
